### ISSUE TITLE
error compiling on Mac OS Mojave  

### ISSUE THREAD

**Issue by lucasaf04** [LibreCAD/libdxfrw#10]
I get 6 errors when compiling the lib on my Mac .

[ 95%] Building CXX object CMakeFiles/dxfrw.dir/src/libdxfrw.cpp.o
/Users/.../libdxfrw-master/src/libdxfrw.cpp:794:27: error: no
      viable conversion from
      'std::__1::__vector_base<std::__1::shared_ptr<DRW_Vertex2D>,
      std::__1::allocator<std::__1::shared_ptr<DRW_Vertex2D> > >::value_type'
      (aka 'std::__1::shared_ptr<DRW_Vertex2D>') to 'DRW_Vertex2D *'
            DRW_Vertex2D *v = ent->vertlist.at(i);
                          ^   ~~~~~~~~~~~~~~~~~~~
/Users/.../libdxfrw-master/src/libdxfrw.cpp:855:21: error: no
      viable conversion from
      'std::__1::__vector_base<std::__1::shared_ptr<DRW_Vertex>,
      std::__1::allocator<std::__1::shared_ptr<DRW_Vertex> > >::value_type' (aka
      'std::__1::shared_ptr<DRW_Vertex>') to 'DRW_Vertex *'
        DRW_Vertex *v = ent->vertlist.at(i);
                    ^   ~~~~~~~~~~~~~~~~~~~
/Users/.../libdxfrw-master/src/libdxfrw.cpp:926:24: error: no
      viable conversion from
      'std::__1::__vector_base<std::__1::shared_ptr<DRW_Coord>,
      std::__1::allocator<std::__1::shared_ptr<DRW_Coord> > >::value_type' (aka
      'std::__1::shared_ptr<DRW_Coord>') to 'DRW_Coord *'
            DRW_Coord *crd = ent->controllist.at(i);
                       ^     ~~~~~~~~~~~~~~~~~~~~~~
/Users/.../libdxfrw-master/src/libdxfrw.cpp:955:28: error: no
      viable conversion from
      'std::__1::__vector_base<std::__1::shared_ptr<DRW_HatchLoop>,
      std::__1::allocator<std::__1::shared_ptr<DRW_HatchLoop> > >::value_type'
      (aka 'std::__1::shared_ptr<DRW_HatchLoop>') to 'DRW_HatchLoop *'
            DRW_HatchLoop *loop = ent->looplist.at(i);
                           ^      ~~~~~~~~~~~~~~~~~~~
/Users/.../libdxfrw-master/src/libdxfrw.cpp:1041:24: error: no
      viable conversion from
      'std::__1::__vector_base<std::__1::shared_ptr<DRW_Coord>,
      std::__1::allocator<std::__1::shared_ptr<DRW_Coord> > >::value_type' (aka
      'std::__1::shared_ptr<DRW_Coord>') to 'DRW_Coord *'
            DRW_Coord *vert = ent->vertexlist.at(i);
                       ^      ~~~~~~~~~~~~~~~~~~~~~
/Users/.../libdxfrw-master/src/libdxfrw.cpp:2573:30: error: 
      reference to type 'const std::shared_ptr<DRW_Vertex>' could not bind to an
      lvalue of type 'DRW_Vertex *'
            pl->appendVertex(v);
                             ^
/Users/.../libdxfrw-master/src/drw_entities.h:757:56: note: 
      passing argument to parameter 'v' here
        void appendVertex (std::shared_ptr<DRW_Vertex> const& v) {
                                                              ^
6 errors generated.
make[2]: *** [CMakeFiles/dxfrw.dir/src/libdxfrw.cpp.o] Error 1
make[1]: *** [CMakeFiles/dxfrw.dir/all] Error 2
make: *** [all] Error 2

**Comment by feragon** [comment]
It should compile now. Can you try again?

**Comment by lucasaf04** [comment]
All correct, thanks.
