### ISSUE TITLE
Regression: DWG file which worked in 0.6.3 no longer works in 1.0.1

### ISSUE THREAD

**Issue by spotrh** [LibreCAD/libdxfrw#56]
I've confirmed that dwg2dxf was able to generate a dxf file without issues with libdxfrw 0.6.3 (and older librecad builds against 0.6.3 loaded it as well), but with the upgrade to 1.0.1 (current HEAD code), neither dwg2dxf nor librecad (tested with 2.2.0rc2 and 2.2.0rc3 built against libdxfrw HEAD) can open the dxf file at issue.

[spot@localhost libdxfrw]$ file ~/sandbox/camotes.dwg 
/home/spot/sandbox/camotes.dwg: DWG AutoDesk AutoCAD 2007/2008/2009

[camotes-dwg.zip](https://github.com/LibreCAD/libdxfrw/files/7765679/camotes-dwg.zip)
[spot@localhost libdxfrw]$ dwg2dxf ~/sandbox/camotes.dwg -v2010 ~/sandbox/camotes.dxf
DWG file error: format 15 error 9
Error reading file /home/spot/sandbox/camotes.dwg

Conversion failed

Problematic DWG file attached to this issue (inside a ZIP to pacify GitHub). Happy to help debug here, but I'm not sure where to start.

**Comment by spotrh** [comment]
This error is now resolved with the latest code in git. Thanks for the fix!

**Comment by lordofbikes** [comment]
many thanks for testing and reporting this :+1:

**Comment by jankratochvil** [comment]
I have tested the new Fedora build but there is still a regression. It now loads the file but there are no fonts:
![librecad-2 2 0-0 13 rc3 fc35 x86_64](https://user-images.githubusercontent.com/1223939/152547772-5ae3327f-30be-413a-9a18-69b8772a6e63.png)
0.6.3 did load it incl. fonts:
![librecad-2 2 0-0 10 rc2 fc35 x86_64](https://user-images.githubusercontent.com/1223939/152547745-91dd70ce-007f-4a62-961f-cc285cda136e.png)
