### ISSUE TITLE
Regression: Text from DWG file which worked in 0.6.3 is no longer visible in 1.0.1

### ISSUE THREAD

**Issue by jankratochvil** [LibreCAD/libdxfrw#59]
Issue #56 fixed error loading the file: [camotes-dwg.zip](https://github.com/LibreCAD/libdxfrw/files/8052818/camotes-dwg.zip)
But now there remains a regression against 0.6.3 that all the text is no longer show:
![librecad-2 2 0-0 13 rc3 fc35 x86_64](https://user-images.githubusercontent.com/1223939/152547772-5ae3327f-30be-413a-9a18-69b8772a6e63.png)
0.6.3 did load it incl. fonts:
![librecad-2 2 0-0 10 rc2 fc35 x86_64](https://user-images.githubusercontent.com/1223939/152547745-91dd70ce-007f-4a62-961f-cc285cda136e.png)

**Comment by lordofbikes** [comment]
Finally found that you mentioned latest Fedora in #56.
This was not caused by `libdxfrw` but LibreCAD.
See LibreCAD/LibreCAD#1488
I think Fedora has fixed this meanwhile.

**Comment by jankratochvil** [comment]
You are right it is fixed upstream now.
Fedora has not fixed it yet.
So now it will: https://src.fedoraproject.org/rpms/librecad/pull-request/1
Thanks.
