### ISSUE TITLE
DRW_Solid thirdCorner and fourthCorner methods return the same point

### ISSUE THREAD

**Issue by TAImatem** [LibreCAD/libdxfrw#64]
https://github.com/LibreCAD/libdxfrw/blob/34b65b020e636cf5b356b17eb6dd55fe162fcc70/src/drw_entities.h#L401-L404
Both return thirdPoint in the code. Not sure what's correct order in this case, since SOLID entity has that weird third and forth points switcheroo.

**Comment by lordofbikes** [comment]
many thanks :+1:
