### ISSUE TITLE
missing ENDSEC in DXF file crashes the application

### ISSUE THREAD

**Issue by lordofbikes** [LibreCAD/libdxfrw#7]
As reported on #librecad IRC channel, this happens with a malicious auto save DXF file.
When ENDSEC code is missing at the end of the DXF file LibreCAD hangs on opening the file.
So the reader must report an error, but should not crash the application.

**Comment by feragon** [comment]
Problematic file, which ends in the ENTITIES section.
[freeze.dxf.txt](https://github.com/LibreCAD/libdxfrw/files/2637388/freeze.dxf.txt)
