### ISSUE TITLE
Uppercase codepage comparison against lower-case strings must fail

### ISSUE THREAD

**Issue by PaulFocus** [LibreCAD/libdxfrw#71]
https://github.com/LibreCAD/libdxfrw/blob/34b65b020e636cf5b356b17eb6dd55fe162fcc70/src/intern/drw_textcodec.cpp#L514-L520

`cp` has been uppercased at the beginning of the method, so comparing it against lower-cased strings will probably not match. Happens in L514 to L520.

**Comment by lordofbikes** [comment]
many thanks :+1:
